[package]
edition = "2021"
rust-version = "1.75"
name = "stardust-xr-server"
version = "0.43.0"
authors = ["Nova King <technobaboo@proton.me>"]
description = "Stardust XR reference display server"
license = "GPLv2"
repository = "https://github.com/StardustXR/stardust-xr-server/"
homepage = "https://stardustxr.org"

[workspace]
members = ["codegen"]

[[bin]]
name = "stardust-xr-server"
path = "src/main.rs"

[features]
default = ["wayland"]
wayland = ["dep:smithay", "dep:xkbcommon"]
xwayland_rootful = []
xwayland_rootless = ["smithay/xwayland"]
profile_tokio = ["dep:console-subscriber", "tokio/tracing"]
profile_app = ["dep:tracing-tracy"]

[package.metadata.appimage]
auto_link = true
auto_link_exclude_list = [
    "libc*",
    "libdl*",
    "libpthread*",
    "ld-linux*",
    "libGL*",
    "libEGL*",
]

[profile.dev.package."*"]
opt-level = 3
[profile.release]
strip = true
lto = true

[dependencies]
color-eyre = { version = "0.6.2", default-features = false }
clap = { version = "4.2.4", features = ["derive"] }
glam = { version = "0.23.0", features = ["mint"] }
lazy_static = "1.4.0"
mint = "0.5.9"
nanoid = "0.4.0"
once_cell = "1.17.1"
parking_lot = "0.12.1"
portable-atomic = { version = "1.2.0", features = ["float", "std"] }
rustc-hash = "1.1.0"
tokio = { version = "1.27.0", features = ["rt-multi-thread", "signal", "time"] }
send_wrapper = "0.6.0"
prisma = "0.1.1"
directories = "5.0.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_repr = "0.1.16"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
global_counter = "0.2.2"
rand = "0.8.5"
atty = "0.2.14"
xkbcommon = { version = "0.7.0", default-features = false, optional = true }
ctrlc = "3.4.1"
libc = "0.2.148"
input-event-codes = "5.16.8"
nix = "0.27.1"
wayland-scanner = "0.31.0"
wayland-backend = "0.3.2"
cluFlock = "1.2.7"
fxtypemap = "0.2.0"

[dependencies.smithay]
# git = "https://github.com/technobaboo/smithay.git" # Until we get stereokit to understand OES samplers and external textures
git = "https://github.com/smithay/smithay.git" # Until we get stereokit to understand OES samplers and external textures
# path = "../smithay"
default-features = false
features = [
    "desktop",
    "backend_drm",
    "backend_egl",
    "renderer_gl",
    "wayland_frontend",
]
version = "*"
optional = true

[dependencies.stereokit]
default-features = false
features = ["linux-egl"]
version = "0.16.9"

[dependencies.console-subscriber]
version = "0.1.8"
optional = true

[dependencies.tracing-tracy]
version = "0.10.4"
optional = true

[dependencies.stardust-xr]
git = "https://github.com/StardustXR/core.git"
branch = "feat/idl"

[dependencies.stardust-xr-server-codegen]
path = "codegen"

# [patch.crates-io.stereokit]
# path = "../stereokit-rs"
# [patch.crates-io.stereokit-sys]
# path = "../stereokit-sys"
